CREATE TABLE IF NOT EXISTS users {
    ID INTEGER  PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    PASSEWORD TEXT NOT NULL,
}

CREATE TABLE IF NOT EXISTS Posts {
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    Title TEXT NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(ID) ON DELETE CASCADE,
}

