CREATE TABLE IF NOT EXISTS users {
    ID INTEGER  PRIMARY KEY AUTOINCREMENT,
    USERNAME CHAR(10) NOT NULL,
    EMAIL CHAR(50) NOT NULL UNIQUE,
    PASSEWORD CHAR(20) NOT NULL,
    datecreation DATE NOT NULL,
    Session TEXT not NULL,
    Expared DATE NOT NULL
}

CREATE TABLE IF NOT EXISTS posts {
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    datecreation TEXT NOT NULL,
    Title TEXT NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(ID) ON DELETE CASCADE
}

CREATE TABLE IF NOT EXISTS comments {
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    datecreation text NOT null,
    Status TEXT,
    user_id INTEGER,
    post_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(ID) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES posts(ID) ON DELETE CASCADE
}

CREATE TABLE if NOT EXISTS category {
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT
}

CREATE TABLE IF NOT EXISTS post_category {
    post_id INTEGER,
    category_id INTEGER,
    FOREIGN KEY (post_id) REFERENCES posts(ID) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES category(ID) ON DELETE CASCADE
}
CREATE TABLE IF NOT EXISTS post_likes {
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Status TEXT,
    user_id INTEGER,
    post_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(ID) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES posts(ID) ON DELETE CASCADE
}

CREATE TABLE IF NOT EXISTS comment_likes {
    ID PRIMARY KEY AUTOINCREMENT,
    Status TEXT,
    user_id INTEGER,
    post_id INTEGER,
     FOREIGN KEY (user_id) REFERENCES users(ID) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES posts(ID) ON DELETE CASCADE
}